(() => {
  const canvas = document.getElementById('map'), ctx = canvas.getContext('2d'), $ = id => document.getElementById(id);
  let live = {transforms: [], plan: null, local_plan: null, goal: null, status: '等待目标'};
  let selectedGoal = null;
  let grids = {}, images = {}, versions = {}, center = [0, 0], scale = 70, fitted = false, dragging = false, dragStart = [0, 0], goalStart = null, goalPreview = null, dpr = 1;
  const qmul=(a,b)=>[a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]];
  const rotate=(q,v)=>{const n=Math.hypot(...q)||1,u=q.map(x=>x/n),p=[...v,0];return qmul(qmul(u,p),[-u[0],-u[1],-u[2],u[3]]).slice(0,3)};
  const compose=(a,b)=>{const r=rotate(a.q,b.p);return {p:a.p.map((v,i)=>v+r[i]),q:qmul(a.q,b.q)}};
  function poses(){const edges=new Map(live.transforms.map(t=>[t.child,t])),memo=new Map(),vis=new Set(),all=new Set();live.transforms.forEach(t=>{all.add(t.parent);all.add(t.child)});function solve(f){if(memo.has(f))return memo.get(f);if(vis.has(f))return null;vis.add(f);const e=edges.get(f),v=!e?{p:[0,0,0],q:[0,0,0,1]}:(solve(e.parent)?compose(solve(e.parent),{p:e.translation,q:e.rotation}):null);vis.delete(f);if(v)memo.set(f,v);return v}all.forEach(solve);return memo}
  const screen=p=>[canvas.clientWidth/2+(p[0]-center[0])*scale,canvas.clientHeight/2-(p[1]-center[1])*scale];
  const world=p=>[center[0]+(p[0]-canvas.clientWidth/2)/scale,center[1]-(p[1]-canvas.clientHeight/2)/scale];
  const yaw=q=>Math.atan2(2*(q[3]*q[2]+q[0]*q[1]),1-2*(q[1]*q[1]+q[2]*q[2]));
  function resize(){dpr=Math.min(devicePixelRatio||1,2);const w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
  function drawLine(a,b,color,width=2,alpha=1){const p=screen(a),q=screen(b);ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=width*dpr;ctx.beginPath();ctx.moveTo(p[0]*dpr,p[1]*dpr);ctx.lineTo(q[0]*dpr,q[1]*dpr);ctx.stroke();ctx.restore()}
  function gridPose(g){const [z,w]=g.origin.rotation,ang=2*Math.atan2(z,w);return {p:[g.origin.position[0],g.origin.position[1],0],q:[0,0,Math.sin(ang/2),Math.cos(ang/2)]}}
  function drawGrid(g,image,alpha){if(!g||!image)return;const o=gridPose(g),p=screen(o.p);ctx.save();ctx.translate(p[0]*dpr,p[1]*dpr);ctx.rotate(-yaw(o.q));ctx.scale(1,-1);ctx.globalAlpha=alpha;ctx.imageSmoothingEnabled=false;ctx.drawImage(image,0,0,g.width*g.resolution*scale*dpr,g.height*g.resolution*scale*dpr);ctx.restore()}
  function makeImage(name,g){if(!g||versions[name]===JSON.stringify(g))return;versions[name]=JSON.stringify(g);const compressed=Uint8Array.from(atob(g.data),c=>c.charCodeAt(0));new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer().then(buf=>{const raw=new Uint8Array(buf),im=new ImageData(g.width,g.height);for(let i=0;i<raw.length;i++){const v=raw[i]-1,o=i*4,c=v<0?100:v>=65?25:v<=20?238:165;im.data[o]=c;im.data[o+1]=c;im.data[o+2]=c;im.data[o+3]=255}const off=document.createElement('canvas');off.width=g.width;off.height=g.height;off.getContext('2d').putImageData(im,0,0);images[name]=off;if(name==='map'&&!fitted)fit()})}
  function drawPath(path,color){if(!path||path.points.length<2)return;const o=path.frame==='map'?null:poses().get(path.frame);for(let i=1;i<path.points.length;i++){const a=o?compose(o,{p:path.points[i-1].position,q:[0,0,0,1]}).p:path.points[i-1].position,b=o?compose(o,{p:path.points[i].position,q:[0,0,0,1]}).p:path.points[i].position;drawLine(a,b,color,3,.9)}}
  function drawRobot(pose){if(!pose)return;const p=screen(pose.p);ctx.save();ctx.translate(p[0]*dpr,p[1]*dpr);ctx.rotate(-yaw(pose.q));ctx.fillStyle='#4fd18b';ctx.strokeStyle='#effff7';ctx.lineWidth=2*dpr;ctx.beginPath();ctx.moveTo(16*dpr,0);ctx.lineTo(-10*dpr,-9*dpr);ctx.lineTo(-6*dpr,0);ctx.lineTo(-10*dpr,9*dpr);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
  function drawGoal(goal){if(!goal)return;const p=screen(goal.position),a=yaw(goal.rotation);ctx.save();ctx.translate(p[0]*dpr,p[1]*dpr);ctx.rotate(-a);ctx.strokeStyle='#ffd166';ctx.fillStyle='#ffd166';ctx.lineWidth=3*dpr;ctx.beginPath();ctx.arc(0,0,9*dpr,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(16*dpr,0);ctx.lineTo(5*dpr,-6*dpr);ctx.lineTo(5*dpr,6*dpr);ctx.closePath();ctx.fill();ctx.restore()}
  function drawPreview(){if(!goalPreview)return;const p=screen(goalPreview.p),a=goalPreview.a;ctx.save();ctx.translate(p[0]*dpr,p[1]*dpr);ctx.rotate(-a);ctx.strokeStyle='#ffd166';ctx.setLineDash([5*dpr,4*dpr]);ctx.lineWidth=2*dpr;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(28*dpr,0);ctx.stroke();ctx.restore()}
  function fit(){const g=grids.map;if(!g)return;const o=gridPose(g),c=[[0,0,0],[g.width*g.resolution,0,0],[0,g.height*g.resolution,0],[g.width*g.resolution,g.height*g.resolution,0]].map(p=>compose(o,{p,q:[0,0,0,1]}).p),xs=c.map(p=>p[0]),ys=c.map(p=>p[1]),w=Math.max(...xs)-Math.min(...xs),h=Math.max(...ys)-Math.min(...ys);center=[(Math.max(...xs)+Math.min(...xs))/2,(Math.max(...ys)+Math.min(...ys))/2];scale=Math.max(8,Math.min(500,(canvas.clientWidth-70)/Math.max(w,.1),(canvas.clientHeight-70)/Math.max(h,.1)));fitted=true}
  function render(){resize();ctx.fillStyle='#171b1e';ctx.fillRect(0,0,canvas.width,canvas.height);const wp=poses(),robot=wp.get('base_footprint')||wp.get('base_link');if(robot&&!dragging&&!fitted)center=[robot.p[0],robot.p[1]];if($('show-map').checked)drawGrid(grids.map,images.map,.94);if($('show-global').checked)drawGrid(grids.global_costmap,images.global_costmap,.28);if($('show-local').checked)drawGrid(grids.local_costmap,images.local_costmap,.4);if($('show-plan').checked){drawPath(live.plan,'#ff5d6c');drawPath(live.local_plan,'#55b7ff')}drawRobot(robot);drawGoal(selectedGoal||live.goal);drawPreview();$('robot-frame').textContent=robot?'base_footprint':'—';if(robot){$('robot-x').textContent=robot.p[0].toFixed(2)+' m';$('robot-y').textContent=robot.p[1].toFixed(2)+' m';$('robot-yaw').textContent=(yaw(robot.q)*180/Math.PI).toFixed(1)+'°'}requestAnimationFrame(render)}
  async function loadMaps(){try{const data=await (await fetch('/api/map',{cache:'no-store'})).json();for(const [name,g] of Object.entries(data)){if(g){grids[name]=g;makeImage(name,g);if(name==='map'){$('map-size').textContent=(g.width*g.resolution).toFixed(1)+' × '+(g.height*g.resolution).toFixed(1)+' m';$('resolution').textContent=(g.resolution*100).toFixed(1)+' cm'}}}}catch(e){console.error(e)}}
  function showGoal(goal){if(!goal)return;$('goal-x').textContent=goal.position[0].toFixed(2)+' m';$('goal-y').textContent=goal.position[1].toFixed(2)+' m';$('goal-yaw').textContent=(yaw(goal.rotation)*180/Math.PI).toFixed(1)+'°';$('send-goal').disabled=false}
  function setZoom(f){const before=world([canvas.clientWidth/2,canvas.clientHeight/2]);scale=Math.max(5,Math.min(1000,scale*f));const after=world([canvas.clientWidth/2,canvas.clientHeight/2]);center[0]+=before[0]-after[0];center[1]+=before[1]-after[1]}
  canvas.addEventListener('pointerdown',e=>{if(e.button===2){fetch('/api/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});return}dragging=true;goalStart=world([e.offsetX,e.offsetY]);dragStart=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-dragStart[0],dy=e.clientY-dragStart[1];if(Math.hypot(dx,dy)>8){goalPreview={p:[goalStart[0],goalStart[1],0],a:Math.atan2(-dy,dx)}}});canvas.addEventListener('pointerup',e=>{if(!dragging)return;dragging=false;const p=goalStart,a=goalPreview?.a||0;selectedGoal={frame:document.body.dataset.fixedFrame||'map',position:[p[0],p[1],0],rotation:[0,0,Math.sin(a/2),Math.cos(a/2)]};showGoal(selectedGoal);goalPreview=null});canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(Math.exp(-e.deltaY*.001))},{passive:false});$('send-goal').onclick=async()=>{const g=selectedGoal;if(!g)return;const button=$('send-goal');button.disabled=true;$('nav-status').textContent='发送中';try{const response=await fetch('/api/goal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({x:g.position[0],y:g.position[1],yaw:yaw(g.rotation),frame:g.frame})});if(!response.ok)throw new Error(`HTTP ${response.status}`);const result=await response.json();if(!result.accepted)throw new Error('Nav2 action 不可用')}catch(error){$('nav-status').textContent=`发送失败: ${error.message}`}finally{button.disabled=false}};$('cancel-goal').onclick=()=>fetch('/api/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});$('zoom-in').onclick=()=>setZoom(1.25);$('zoom-out').onclick=()=>setZoom(.8);$('fit').onclick=fit;
  const stream=new EventSource('/events');stream.onopen=()=>{$('connection').className='connection live';$('connection').lastElementChild.textContent='实时连接'};stream.onerror=()=>{$('connection').className='connection error';$('connection').lastElementChild.textContent='连接中断，正在重试'};stream.onmessage=e=>{live=JSON.parse(e.data);if(!selectedGoal)showGoal(live.goal);$('nav-status').textContent=live.status;$('tf-state').textContent=live.transforms.length?'实时':'等待';$('tf-dot').className=live.transforms.length?'live':'';$('plan-state').textContent=live.plan?.points?.length?`${live.plan.points.length} 点`:'等待';$('plan-dot').className=live.plan?.points?.length?'live':'';loadMaps()};['show-map','show-global','show-local','show-plan'].forEach(id=>$(id).onchange=()=>{});loadMaps();render();
})();
