(() => {
  const canvas = document.getElementById('map'), ctx = canvas.getContext('2d');
  const $ = id => document.getElementById(id);
  let live = {transforms: [], scan: null, trajectory: [], map_version: 0};
  let map = null, mapImage = null, loadedVersion = -1, loadingMap = false;
  let scale = 80, center = [0, 0], fitted = false, following = true, dragging = false, pointer = [0, 0], dpr = 1;

  const quatMul = (a,b) => [a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]];
  const rotate = (q,v) => { const n=Math.hypot(...q)||1,u=q.map(x=>x/n),p=[...v,0]; return quatMul(quatMul(u,p),[-u[0],-u[1],-u[2],u[3]]).slice(0,3); };
  const compose = (a,b) => { const r=rotate(a.q,b.p); return {p:a.p.map((v,i)=>v+r[i]),q:quatMul(a.q,b.q)}; };
  function poses() {
    const edges=new Map(live.transforms.map(t=>[t.child,t])), all=new Set(), memo=new Map(), visiting=new Set();
    live.transforms.forEach(t=>{all.add(t.parent);all.add(t.child)});
    function solve(frame){if(memo.has(frame))return memo.get(frame);if(visiting.has(frame))return null;visiting.add(frame);const e=edges.get(frame);let p;if(!e)p={p:[0,0,0],q:[0,0,0,1]};else{const parent=solve(e.parent);p=parent?compose(parent,{p:e.translation,q:e.rotation}):null}visiting.delete(frame);if(p)memo.set(frame,p);return p} all.forEach(solve);return memo;
  }
  const screen = p => [canvas.clientWidth/2+(p[0]-center[0])*scale,canvas.clientHeight/2-(p[1]-center[1])*scale];
  const world = p => [center[0]+(p[0]-canvas.clientWidth/2)/scale,center[1]-(p[1]-canvas.clientHeight/2)/scale];
  function resize(){dpr=Math.min(devicePixelRatio||1,2);const w=Math.round(canvas.clientWidth*dpr),h=Math.round(canvas.clientHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}}
  function line(a,b,color,width=1,alpha=1){const p=screen(a),q=screen(b);ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle=color;ctx.lineWidth=width*dpr;ctx.beginPath();ctx.moveTo(p[0]*dpr,p[1]*dpr);ctx.lineTo(q[0]*dpr,q[1]*dpr);ctx.stroke();ctx.restore()}
  function mapPose(){if(!map)return null;const [z,w]=map.origin.rotation,yaw=2*Math.atan2(z,w);return {p:[map.origin.position[0],map.origin.position[1],0],q:[0,0,Math.sin(yaw/2),Math.cos(yaw/2)]}}
  function drawMap(){if(!map||!mapImage||!$('show-map').checked)return;const origin=mapPose(),p=screen(origin.p),yaw=2*Math.atan2(origin.q[2],origin.q[3]);ctx.save();ctx.translate(p[0]*dpr,p[1]*dpr);ctx.rotate(-yaw);ctx.scale(1,-1);ctx.globalAlpha=.92;ctx.imageSmoothingEnabled=false;ctx.drawImage(mapImage,0,0,map.width*map.resolution*scale*dpr,map.height*map.resolution*scale*dpr);ctx.restore()}
  function drawGrid(){if(!$('show-grid').checked)return;const tl=world([0,0]),br=world([canvas.clientWidth,canvas.clientHeight]),step=scale<30?5:scale<80?2:1;ctx.save();ctx.font=`${10*dpr}px ui-monospace`;for(let x=Math.floor(tl[0]/step)*step;x<=br[0];x+=step){line([x,tl[1]],[x,br[1]],'#71808a',1,.18);const p=screen([x,0]);ctx.fillStyle='#7d8991';ctx.fillText(`${x}m`,p[0]*dpr,12*dpr)}for(let y=Math.floor(br[1]/step)*step;y<=tl[1];y+=step)line([tl[0],y],[br[0],y],'#71808a',1,.18);ctx.restore()}
  function drawTrajectory(){if(!$('show-trajectory').checked||live.trajectory.length<2)return;for(let i=1;i<live.trajectory.length;i++)line(live.trajectory[i-1],live.trajectory[i],'#b693ff',2.5,.9)}
  function drawScan(worldPoses){if(!$('show-scan').checked||!live.scan)return;const base=worldPoses.get(live.scan.frame);if(!base)return;ctx.fillStyle='#ff6470';const stride=Math.max(1,Math.floor(live.scan.ranges.length/1200));for(let i=0;i<live.scan.ranges.length;i+=stride){const r=live.scan.ranges[i];if(!Number.isFinite(r)||r<live.scan.range_min||r>live.scan.range_max)continue;const a=live.scan.angle_min+i*live.scan.angle_increment,point=compose(base,{p:[r*Math.cos(a),r*Math.sin(a),0],q:[0,0,0,1]}).p,p=screen(point);ctx.fillRect((p[0]-1)*dpr,(p[1]-1)*dpr,2*dpr,2*dpr)}}
  function robotPose(worldPoses){return worldPoses.get('base_footprint')||worldPoses.get('base_link')||null}
  function drawRobot(pose){if(!pose)return;const yaw=Math.atan2(2*(pose.q[3]*pose.q[2]+pose.q[0]*pose.q[1]),1-2*(pose.q[1]**2+pose.q[2]**2)),p=screen(pose.p),r=11*dpr;ctx.save();ctx.translate(p[0]*dpr,p[1]*dpr);ctx.rotate(-yaw);ctx.fillStyle='#4fd18b';ctx.strokeStyle='#eafbf2';ctx.lineWidth=1.5*dpr;ctx.beginPath();ctx.moveTo(15*dpr,0);ctx.lineTo(-9*dpr,-9*dpr);ctx.lineTo(-5*dpr,0);ctx.lineTo(-9*dpr,9*dpr);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();return yaw}
  function updateScale(){const options=[.1,.2,.5,1,2,5,10,20,50],meters=options.find(v=>v*scale>=55)||50;$('scale-bar').style.width=`${meters*scale}px`;$('scale-label').textContent=`${meters} m`}
  function render(){resize();ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#171b1e';ctx.fillRect(0,0,canvas.width,canvas.height);const wp=poses(),robot=robotPose(wp);if(following&&robot&&!dragging)center=[robot.p[0],robot.p[1]];drawGrid();drawMap();drawTrajectory();drawScan(wp);const yaw=drawRobot(robot);if(robot){$('robot-frame').textContent=wp.has('base_footprint')?'base_footprint':'base_link';$('robot-x').textContent=`${robot.p[0].toFixed(3)} m`;$('robot-y').textContent=`${robot.p[1].toFixed(3)} m`;$('robot-yaw').textContent=`${(yaw*180/Math.PI).toFixed(1)}°`}updateScale();requestAnimationFrame(render)}
  async function loadMap(){if(loadingMap||live.map_version===loadedVersion)return;loadingMap=true;try{const response=await fetch('/api/map',{cache:'no-store'}),next=await response.json();if(next){map=next;loadedVersion=live.map_version;const compressed=Uint8Array.from(atob(next.data),c=>c.charCodeAt(0)),stream=new Blob([compressed]).stream().pipeThrough(new DecompressionStream('gzip')),raw=new Uint8Array(await new Response(stream).arrayBuffer()),image=new ImageData(next.width,next.height);for(let i=0;i<raw.length;i++){const value=raw[i]-1,o=i*4,c=value<0?100:value>=65?25:value<=20?238:165;image.data[o]=c;image.data[o+1]=c;image.data[o+2]=c;image.data[o+3]=255}const off=document.createElement('canvas');off.width=next.width;off.height=next.height;off.getContext('2d').putImageData(image,0,0);mapImage=off;$('map-size').textContent=`${(next.width*next.resolution).toFixed(1)} × ${(next.height*next.resolution).toFixed(1)} m`;$('resolution').textContent=`${(next.resolution*100).toFixed(1)} cm`;$('map-state').textContent='实时';$('map-dot').className='live';if(!fitted)fit()}}catch(e){console.error('Map update failed',e);$('map-state').textContent='解码失败'}finally{loadingMap=false}}
  function fit(){if(!map)return;const origin=mapPose(),corners=[[0,0,0],[map.width*map.resolution,0,0],[0,map.height*map.resolution,0],[map.width*map.resolution,map.height*map.resolution,0]].map(p=>compose(origin,{p,q:[0,0,0,1]}).p),xs=corners.map(p=>p[0]),ys=corners.map(p=>p[1]),w=Math.max(...xs)-Math.min(...xs),h=Math.max(...ys)-Math.min(...ys);center=[(Math.max(...xs)+Math.min(...xs))/2,(Math.max(...ys)+Math.min(...ys))/2];scale=Math.max(8,Math.min(500,(canvas.clientWidth-80)/Math.max(w,.1),(canvas.clientHeight-80)/Math.max(h,.1)));fitted=true;following=false;$('follow').classList.remove('active')}
  function setZoom(factor,anchor=[canvas.clientWidth/2,canvas.clientHeight/2]){const before=world(anchor);scale=Math.max(5,Math.min(1000,scale*factor));const after=world(anchor);center[0]+=before[0]-after[0];center[1]+=before[1]-after[1]}
  const controls={linear:$('linear-speed'),angular:$('angular-speed')};let driveTimer=null,driveDirection=null;
  function updateSpeedLabels(){$('linear-value').textContent=`${Number(controls.linear.value).toFixed(2)} m/s`;$('angular-value').textContent=`${Number(controls.angular.value).toFixed(2)} rad/s`}
  function sendVelocity(linear_x,angular_z){fetch('/api/cmd_vel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({linear_x,angular_z})}).then(response=>{if(!response.ok)throw new Error(`HTTP ${response.status}`);$('teleop-state').textContent=linear_x||angular_z?'控制中':'已停止'}).catch(error=>{$('teleop-state').textContent='控制失败';console.error('cmd_vel failed',error)})}
  function velocityFor(direction){const linear=Number(controls.linear.value),angular=Number(controls.angular.value);return direction==='forward'?[linear,0]:direction==='backward' ? [-linear,0]:direction==='left'?[0,angular]:[0,-angular]}
  function startDrive(direction){stopDrive();driveDirection=direction;const send=()=>{const [linear,angular]=velocityFor(direction);sendVelocity(linear,angular)};send();driveTimer=setInterval(send,100)}
  function stopDrive(){if(driveTimer){clearInterval(driveTimer);driveTimer=null}driveDirection=null;sendVelocity(0,0)}
  controls.linear.addEventListener('input',updateSpeedLabels);controls.angular.addEventListener('input',updateSpeedLabels);updateSpeedLabels();
  document.querySelectorAll('[data-drive]').forEach(button=>{button.addEventListener('pointerdown',()=>startDrive(button.dataset.drive));button.addEventListener('pointerup',stopDrive);button.addEventListener('pointercancel',stopDrive);button.addEventListener('pointerleave',e=>{if(e.buttons)stopDrive()})});$('stop').addEventListener('click',stopDrive);
  const keys={w:'forward',a:'left',s:'backward',d:'right'};document.addEventListener('keydown',event=>{const direction=keys[event.key.toLowerCase()];if(direction&&!event.repeat){event.preventDefault();startDrive(direction)}});document.addEventListener('keyup',event=>{if(keys[event.key.toLowerCase()]){event.preventDefault();stopDrive()}});window.addEventListener('blur',stopDrive);document.addEventListener('visibilitychange',()=>{if(document.hidden)stopDrive()});
  canvas.addEventListener('pointerdown',e=>{dragging=true;following=false;$('follow').classList.remove('active');pointer=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;center[0]-=(e.clientX-pointer[0])/scale;center[1]+=(e.clientY-pointer[1])/scale;pointer=[e.clientX,e.clientY]});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(Math.exp(-e.deltaY*.001),[e.offsetX,e.offsetY])},{passive:false});$('zoom-in').onclick=()=>setZoom(1.25);$('zoom-out').onclick=()=>setZoom(.8);$('fit').onclick=fit;$('follow').onclick=()=>{following=!following;$('follow').classList.toggle('active',following)};
  const stream=new EventSource('/events');stream.onopen=()=>{$('connection').className='connection live';$('connection').lastElementChild.textContent='实时连接'};stream.onerror=()=>{$('connection').className='connection error';$('connection').lastElementChild.textContent='连接中断，正在重试'};stream.onmessage=e=>{try{live=JSON.parse(e.data);if(live.map_version!==loadedVersion)loadMap();const now=Date.now()/1000;$('tf-state').textContent=live.transforms.length?'实时':'等待';$('tf-dot').className=live.transforms.length?'live':'';$('scan-state').textContent=live.scan?'实时':'等待';$('scan-dot').className=live.scan?'live':'';$('trajectory-state').textContent=live.trajectory.length?`${live.trajectory.length} 点`:'等待';$('trajectory-dot').className=live.trajectory.length?'live':''}catch(err){console.error(err)}};render();
})();
